version: 2
workflows:
  version: 2
  build_and_test:
    jobs:
      - vet
      - test:
          requires:
            - vet
      - compile:
          requires:
            - vet
jobs:
  vet:
    docker:
      - image: circleci/golang:latest
    working_directory: /go/src/github.com/u-root/dhcp4
    steps:
      - checkout
      - run:
          name: Check vendored dependencies
          command: |
            go get -u github.com/golang/dep/cmd/dep
            dep status
      - run:
          name: go vet
          command: go tool vet `find -name \*.go | grep -v ^./vendor`
      - run:
          name: golint
          command: |
            go get -u github.com/golang/lint/golint
            golint ./
            golint ./dhcp4opts/...
            golint ./dhcp4client/...
            golint ./internal/...
  test:
    docker:
      - image: circleci/golang:latest
    working_directory: /go/src/github.com/u-root/dhcp4
    environment:
      - CGO_ENABLED: 0
    steps:
      - checkout
      - run:
          name: Test dhcp4
          command: |
            go test -a -ldflags '-s' ./...
      - run:
          name: Test coverage of dhcp4
          command: |
            go test -cover ./...
  compile:
    docker:
      - image: circleci/golang:latest
    working_directory: /go/src/github.com/u-root/dhcp4
    environment:
      - CGO_ENABLED: 0
    steps:
      - checkout
      - run:
          name: build all tools
          command: |
            go build -a -ldflags '-s' ./...
